services:
  zellij-bookworm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:bookworm
        DISTRO: bookworm
        ZELLIJ_VERSION: ${ZELLIJ_VERSION}
    volumes:
      - ./output-bookworm:/output

  zellij-noble:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ubuntu:24.04
        DISTRO: noble
        ZELLIJ_VERSION: ${ZELLIJ_VERSION}
    volumes:
      - ./output-noble:/output

  zellij-jammy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ubuntu:22.04
        DISTRO: jammy
        ZELLIJ_VERSION: ${ZELLIJ_VERSION}
    volumes:
      - ./output-jammy:/output

  zellij-plucky:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ubuntu:25.04
        DISTRO: plucky
        ZELLIJ_VERSION: ${ZELLIJ_VERSION}
    volumes:
      - ./output-plucky:/output
