services:
  zellij-debian:
    build:
      context: .
      dockerfile: Dockerfile
      target: export
      args:
        BASE_IMAGE: debian:bookworm
        DISTRO: debian-bookworm
    volumes:
      - ./output-debian:/output

  zellij-ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
      target: export
      args:
        BASE_IMAGE: ubuntu:24.04
        DISTRO: ubuntu-24.04
    volumes:
      - ./output-ubuntu:/output

