services:
  zellij-bookworm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:bookworm
        DISTRO: bookworm
    volumes:
      - ./output-bookworm:/output

  zellij-noble:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ubuntu:24.04
        DISTRO: noble
    volumes:
      - ./output-noble:/output

  zellij-jammy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ubuntu:22.04
        DISTRO: jammy
    volumes:
      - ./output-jammy:/output
